fix: byteArray encoding for less than 31 chars
starknet-io/starknet.js pull request #1011
Opened 2024-03-13 15:33 UTC by PhilippeR26

## Motivation and Resolution
Solve #1003 
If a ByteArray has less than 31 characters, the data array has to be empty (was containing one "0x00" item)

## Usage related changes
N/A

## Development related changes
N/A

## Checklist:

- [x] Performed a self-review of the code
- [x] Rebased to the last commit of the target branch (or merged it into my branch)
- [x] Linked the issues which this PR resolves
- [x] Documented the changes in code (API docs will be generated automatically)
- [x] Updated the tests
- [x] All tests are passing

2024-03-13 15:40 UTC, ivpavici approved these changes

2024-03-13 18:59 UTC, DelevoXDG requested changes
Should probably fix this in [typedData.ts](https://github.com/starknet-io/starknet.js/blob/6cd35aa26d47d4f3a594349d65792fd1f368ba67/src/utils/typedData.ts#L65) as well

2024-03-13 19:04 UTC, PhilippeR26 commented
@penovicp

2024-03-13 22:19 UTC, tabaktoni approved these changes
LGTM!

2024-03-14 07:35 UTC, penovicp approved these changes

2024-03-14 09:47 UTC, merged