feat: handling of cairo u512 type
starknet-io/starknet.js pull request #1022
Opened 2024-03-19 16:15 UTC by PhilippeR26

## Motivation and Resolution
The new u512 Cairo type is now implemented.
Solve issue #1013.
 According to https://github.com/starkware-libs/cairo/blob/07484c52791b76abcc18fd86265756904557d0d2/corelib/src/test/integer_test.cairo#L767

The raw format is :
```
{
    limb0: u128, // lower weight
    limb1: u128,
    limb2: u128,
    limb3: u128, // upper weight
};
```

## Usage related changes

User send a BigNumberish, and receive a bigint.

```typescript
await myContract0.my_function(553844998243714947043252949842317834769n);
await myContract1.my_function(cairo.uint512("0xa9d2d1501ad0a2eb5337a9d2d1501ad0a2eb5337a9d2d1501ad0a2eb5337a9d2d1501ad0a2eb5337a9d2d1501ad0a2eb5337")); 
await myContract2.my_function(12345678, '13456789765', '0xe23a40b543f', 1534566734334n);
```

```typescript
const a2: Uint512 = {
  limb0: "0xeb5337d9a885be310x9365205a414fdd",
  limb1: "0x1fd465baff2ba9d2d1501ad0a2eb5337",
  limb2: "0x05f7cd1fd465baff2ba9d2d1501ad0a2",
  limb3: "0x2eb5337d9a885be319366b5205a414fd"
};
```

## Development related changes

A new file is in utils/cairoDataTypes, inspired from the Cairo u256 type.

## Checklist:

- [x] Performed a self-review of the code
- [x] Rebased to the last commit of the target branch (or merged it into my branch)
- [x] Linked the issues which this PR resolves
- [x] Documented the changes in code (API docs will be generated automatically)
- [x] Updated the tests
- [x] All tests are passing

2024-03-20 09:14 UTC, PhilippeR26 commented
@haroune-mohammedi 

For u512, Starknet.js is waiting a Bignumberish.

2024-03-22 07:57 UTC, tabaktoni requested changes
Look like there is some issue on validate ?

2024-03-22 08:18 UTC, ivpavici commented on www/docs/guides/define_call_message.md
> +Starknet is waiting for 4 u128, the first one has the lowest wight.
wight?

2024-03-22 08:39 UTC, PhilippeR26 commented
> Look like there is some issue on validate ?

Problem from pr #1007

Solved.

2024-03-22 09:22 UTC, tabaktoni approved these changes
LGTM!

2024-03-22 11:04 UTC, ivpavici commented on src/utils/cairoDataTypes/uint512.ts
> +   * @param bigNumberish BigNumberish value representing uin256
```suggestion
   * @param bigNumberish BigNumberish value representing uint256
```

2024-03-22 12:20 UTC, PhilippeR26 commented on src/utils/cairoDataTypes/uint512.ts
> +   * @param bigNumberish BigNumberish value representing uin256
In fact : `u512`
Corrected

2024-03-22 12:23 UTC, ivpavici approved these changes

2024-03-22 13:39 UTC, merged

2024-03-27 11:55 UTC, haroune-mohammedi commented
> @haroune-mohammedi
> 
> For u512, Starknet.js is waiting a Bignumberish.

Will be addressed here https://github.com/keep-starknet-strange/abi-wan-kanabi/issues/68