docs: adding missing jsdocs on methods
starknet-io/starknet.js pull request #1036
Opened 2024-03-23 22:00 UTC by ikrcatov

Closes  #1033
## Motivation and Resolution

...

### RPC version (if applicable)

...

## Usage related changes

- Change 1.
- ...

## Development related changes

- Change 1.
- ...

## Checklist:

- [ ] Performed a self-review of the code
- [ ] Rebased to the last commit of the target branch (or merged it into my branch)
- [ ] Linked the issues which this PR resolves
- [ ] Documented the changes in code (API docs will be generated automatically)
- [ ] Updated the tests
- [ ] All tests are passing

2024-03-26 15:31 UTC, ivpavici commented on src/account/default.ts
> +   * Estimate the invoke fee for a given set of calls.
sorry for forgetting about mentioning this, but the interface (/account/interface.ts) has docs for these [methods](https://github.com/starknet-io/starknet.js/blob/b16db6db7120ba57a8dab13516a8ccb0ad9f3c78/src/account/interface.ts#L42)
...maybe not for all of them, so for the missing ones I would add docs, and remove where they are already present in the interface.
The same thing should be done for `contract.ts` and `signer.ts`

2024-03-26 17:23 UTC, ivpavici commented on src/wallet/connect.ts
> +/**
These files will be removed as per this PR:
https://github.com/starknet-io/starknet.js/pull/1042

2024-03-26 18:39 UTC, tabaktoni requested changes
Also when updated on develop branch and test pass, rebase to next-version to be done

2024-03-29 15:22 UTC, ivpavici requested changes

2024-03-29 15:22 UTC, ivpavici commented on src/account/default.ts
> +   * Retrieves the StarkNet name associated with a given address.
```suggestion
   * Retrieves the Starknet name associated with a given address.
```

If I don't point it out here in review, someone will make a PR xD

2024-03-29 15:22 UTC, ivpavici commented on src/account/default.ts
> +   * @param {BigNumberish} address - The Ethereum address for which to retrieve the StarkNet name. Defaults to the wallet address.
```suggestion
   * @param {BigNumberish} address - The address for which to retrieve the Starknet name. Defaults to the wallet address.
```

2024-03-29 15:22 UTC, ivpavici commented on src/channel/rpc_0_6.ts
> +   * Sets the chain ID for the Starknet.
```suggestion
   * Sets the Starknet chain ID.
```

2024-03-29 15:22 UTC, ivpavici commented on src/channel/rpc_0_6.ts
> +   * Retrieves the spec version of the Starknet chain.
```suggestion
   * Returns the version of the Starknet JSON-RPC specification being used
```

2024-03-29 15:22 UTC, ivpavici commented on src/channel/rpc_0_6.ts
> +   * Retrieves the nonce for a given contract address and block identifier.
For all of these descriptions in the rpc files, it's possible to go through the spec file and compare the summary!
https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json

2024-03-29 15:22 UTC, ivpavici commented on src/provider/extensions/starknetId.ts
> +   * @param {ProviderInterface} provider - The Ethereum provider interface.
```suggestion
   * @param {ProviderInterface} provider - The provider interface.
```

please check all instances of "Ethereum" and remove!

2024-03-29 15:22 UTC, ivpavici commented on src/utils/contract.ts
> + * Checks if a given contract is a Sierra contract.
```suggestion
 * Checks if a given contract is in Sierra (Safe Intermediate Representation) format.
```

2024-04-08 07:49 UTC, PhilippeR26 commented
I will not comment function by function, but hereunder are my global thoughts :
- Many double JSDoc for classes that are implementing an interface (keep only interface JSDoc).
- When a function is not exported, the interest to add JSDoc is questionable , as it will not be visible in the API documentation.

Globally, a lack of examples, context, tips.
As these JSDoc are mainly copy/paste/rewording of functions signature, the added value for devs seems not very high.

2024-04-15 14:47 UTC, ivpavici commented on src/wallet/account.ts
>    override execute(calls: AllowArray<Call>) {
we can remove JSDoc from all methods that override

2024-04-15 14:47 UTC, ivpavici commented on src/wallet/account.ts
> +   * Registers a callback function to be executed when the account changes.
we can remove all of these JSDOCs from just public methods, we need only on the ones that are exported...

`onAccountChange` is exported in the connect file

2024-04-15 14:47 UTC, ivpavici commented on src/utils/typedData.ts
> +/**
JSDoc not needed since the function is not exported

2024-04-15 14:47 UTC, ivpavici commented on src/utils/typedData.ts
> + * Checks if the given StarkNet type is a Merkle tree type.
```suggestion
 * Checks if the given Starknet type is a Merkle tree type.
```

2024-04-15 14:47 UTC, ivpavici commented on src/utils/typedData.ts
> + * @param {StarkNetType} type - The StarkNet type to check.
```suggestion
 * @param {StarknetType} type - The Starknet type to check.
```

2024-04-15 14:47 UTC, ivpavici commented on src/utils/responseParser/rpc.ts
> +  /**
All the JSDoc here not needed since the functions are not exported or private

2024-04-15 14:47 UTC, ivpavici commented on src/utils/provider.ts
> +  /**
private, can be removed

2024-04-15 14:47 UTC, ivpavici commented on src/utils/hash/classHash.ts
> +function hashAbi(sierra: CompiledSierra): bigint {
JSDoc not needed since the function is not exported

2024-04-15 14:47 UTC, ivpavici commented on src/utils/calldata/validate.ts
> +/**
JSDoc not needed since the function is not exported

2024-04-15 14:47 UTC, ivpavici commented on src/utils/calldata/validate.ts
> +/**
JSDoc not needed since the function is not exported

2024-04-15 14:47 UTC, ivpavici commented on src/utils/calldata/validate.ts
> +/**
JSDoc not needed since the function is not exported

all of the below actually

2024-04-15 14:47 UTC, ivpavici commented on src/utils/calldata/tuple.ts
> +/**
JSDoc not needed on all below since the functions are not exported

2024-04-15 14:47 UTC, ivpavici commented on src/utils/calldata/requestParser.ts
> +/**
jsdoc not needed since it's not exported

2024-04-15 14:47 UTC, ivpavici commented on src/utils/calldata/propertyOrder.ts
> +  /**
jsdoc not needed since it's not exported

2024-04-15 14:47 UTC, ivpavici commented on src/utils/calldata/propertyOrder.ts
> +/**
jsdoc not needed since it's not exported

and all in file

2024-04-15 14:47 UTC, ivpavici commented on src/signer/ethSigner.ts
> +  /**
All of these can be removed since they are documented in the "SignerInterface"

2024-04-15 14:47 UTC, ivpavici commented on src/signer/default.ts
> +  /**
can be removed

2024-04-15 14:47 UTC, ivpavici commented on src/provider/rpc.ts
> +  /**
all can be removed

2024-04-15 14:47 UTC, ivpavici commented on src/provider/extensions/starknetId.ts
> +  /**
all can be removed

2024-04-15 14:47 UTC, ivpavici commented on src/channel/rpc_0_7.ts
> +  /**
all can be removed

2024-04-15 14:47 UTC, ivpavici commented on src/channel/rpc_0_6.ts
> +  /**
all can be removed

2024-04-15 14:47 UTC, ivpavici commented on src/account/default.ts
> +  /**
all can be removed since not exported

2024-04-18 13:48 UTC, ivpavici commented on src/utils/typedData.ts
> + * @param {StarknetType} type - The StarkNet type to check.
```suggestion
 * @param {StarknetType} type - The Starknet type to check.
```

2024-04-18 13:48 UTC, ivpavici commented on src/utils/address.ts
> + * Computes the checksum address for the given Ethereum address.
```suggestion
 * Computes the checksum address for the given Starknet address.
```

2024-04-18 13:48 UTC, ivpavici commented on src/utils/address.ts
> + * @param {BigNumberish} address - The Ethereum address to compute the checksum for.
```suggestion
 * @param {BigNumberish} address - The address to compute the checksum for.
```

2024-04-18 13:48 UTC, ivpavici commented on src/utils/starknetId.ts
> +/**
This one is left to remove

2024-04-19 13:12 UTC, ivpavici commented on src/utils/address.ts
> + * @param {BigNumberish} address - The Ethereum address to compute the checksum for.
```suggestion
 * @param {BigNumberish} address - The address to compute the checksum for.
```

2024-04-19 13:57 UTC, ivpavici commented on src/utils/calldata/cairo.ts
> + * Checks if a given type exists in the provided enumeration.
```suggestion
 * Checks if a given type is an enum.
```

2024-04-19 13:57 UTC, ivpavici commented on src/utils/calldata/cairo.ts
> + * Checks if a given type exists in a collection of structs.
```suggestion
 * Checks if a given type is a struct.
```

2024-04-19 13:58 UTC, ivpavici approved these changes

2024-04-19 13:59 UTC, merged