chore/add JsDoc for address.ts file
starknet-io/starknet.js pull request #1096
Opened 2024-04-23 18:28 UTC by BlackStarkGoku

I simply added JSDocs for address.ts file, won't affect tests or code. If everything is alright, I can add more.

2024-04-24 10:11 UTC, ivpavici reviewed
looks like a good direction!
please resolve merge conflicts :)

2024-04-24 12:30 UTC, PhilippeR26 commented on src/utils/address.ts
> + * // result = "0x07ee790591d9fa3efc87067d95a643f8455e0b8190eb8cb7bfd39e4fb7571fdf"
Address is a string. To use between quotes.
You should use an address that needs more zeros (for example 3), as we have a function that optionally add a zero to have an odd number of characters.

2024-04-29 09:52 UTC, PhilippeR26 commented
Target branch has to be `next-version`

2024-04-29 11:38 UTC, PhilippeR26 commented on src/utils/address.ts
> + * // result = "true"
Result is a boolean, not a string.
So, double quotes have to be removed.

2024-04-29 11:47 UTC, PhilippeR26 commented on src/utils/encode.ts
Encode functions are accessible for the users by using the namespace `encode`.
The examples have to be usable by the users.
So, you have to add in all examples in this file  : `encode.` before each use of an encoding function .

2024-04-29 11:56 UTC, PhilippeR26 commented on src/utils/encode.ts
To be consistent in all the project, use `* // result = ` to display the result (as you made perfectly in `address.ts`).

2024-04-29 12:02 UTC, PhilippeR26 commented on src/utils/encode.ts
> + * const string = arrayBufferToString({0: 72, 1: 105});
This example isn't working :
```
error TS2353: Object literal may only specify known properties, and '0' does not exist in type 'ArrayBuffer'.
const string = encode.arrayBufferToString({0: 72, 1: 105});
                                                                     Î
```

2024-04-29 12:08 UTC, PhilippeR26 commented on src/utils/encode.ts
> + * console.log(byteArray); // Outputs: Uint8Array {0: 72, 1: 105}
Have you tested your example?
The result is not a struct, but an array (as the name is explaining) :
```
[ 72, 105 ]
```

2024-04-29 12:14 UTC, PhilippeR26 commented on src/utils/encode.ts
> + * console.log(byteArray); // Outputs: Uint8Array {0: 72, 1: 105, 2: 108, 3: 108, 4: 111}
Response is not an object, but an array : 
```
[ 72, 101, 108, 108, 111 ]
```

2024-04-29 12:14 UTC, PhilippeR26 commented on src/utils/encode.ts
> + * @param {Uint8Array} b The decoded Uint8Array.
ArrayBuffer

2024-04-29 12:25 UTC, PhilippeR26 commented on src/utils/encode.ts
>   * @returns format: hex-string
param missing.

2024-04-29 12:25 UTC, PhilippeR26 commented on src/utils/encode.ts
>   * Convert array buffer to hex-string
param missing.

2024-04-29 12:26 UTC, PhilippeR26 commented on src/utils/encode.ts
>   * @returns format: hex-string
Could you add that it's without "0x"

2024-04-29 12:33 UTC, PhilippeR26 commented on src/utils/encode.ts
>  function padString(str: string, length: number, left: boolean, padding = STRING_ZERO): string {
This function is not exported, so JSDoc isn't really useful.
But it's made, so keep it (without `encode.` prefix, as it's not exported).

2024-04-29 12:37 UTC, PhilippeR26 commented on src/utils/encode.ts
> + * const myString = 'hello';
This function is used for hex string, not for text. Please change to a hex num example.

2024-04-29 12:58 UTC, PhilippeR26 commented on src/utils/encode.ts
Each parameter that has a default value has to be written with :
```
@param {type} [name='0']
```

2024-04-29 13:01 UTC, PhilippeR26 commented on src/utils/encode.ts
> + * console.log(formattedHex); // Outputs: '0x023abc' (padded to ensure even length)
Could you modify the definition above (line 257) to explain the even length?

2024-04-29 13:03 UTC, PhilippeR26 requested changes
Several things to correct (some comments are valid for the whole encode.ts file).

2024-04-29 14:20 UTC, PhilippeR26 commented on src/utils/encode.ts
> + * console.log(byteArray); // Outputs: Uint8Array {0: 72, 1: 105}
maybe, but ts-node is reporting :
![image](https://github.com/starknet-io/starknet.js/assets/81040730/d0ecf16a-f1f9-4a68-9409-5167c6e93ec8)
So, Uint8Array is an array... sounds so logical...

2024-04-29 14:21 UTC, PhilippeR26 commented on src/utils/encode.ts
> + * console.log(byteArray); // Outputs: Uint8Array {0: 72, 1: 105, 2: 108, 3: 108, 4: 111}
![image](https://github.com/starknet-io/starknet.js/assets/81040730/12985fd1-0d53-45a1-818e-4fe093589795)

2024-04-30 17:33 UTC, PhilippeR26 requested changes
One change requested.

2024-04-30 17:46 UTC, PhilippeR26 approved these changes
@ivpavici Finally lgfm

2024-05-02 13:10 UTC, ivpavici approved these changes

2024-05-02 13:10 UTC, merged