docs: add example to provider.ts in utils
starknet-io/starknet.js pull request #1114
Opened 2024-05-01 22:22 UTC by vibenedict

## Motivation and Resolution

...

### RPC version (if applicable)

...

## Usage related changes

- Change 1.
- ...

## Development related changes

- Change 1.
- ...

## Checklist:

- [ ] Performed a self-review of the code
- [ ] Rebased to the last commit of the target branch (or merged it into my branch)
- [ ] Linked the issues which this PR resolves
- [ ] Documented the changes in code (API docs will be generated automatically)
- [ ] Updated the tests
- [ ] All tests are passing

2024-05-02 18:42 UTC, vibenedict commented
Done

2024-05-03 09:47 UTC, ivpavici commented
@vibenedict thanks for resolving conflicts, but my previous comment is not yet addressed, regardingg adding missing `@param` on all functions?

2024-05-07 13:50 UTC, PhilippeR26 requested changes
As explained in Telegram https://t.me/c/2066195975/59 ,
please follow very rigorously  the template of this PR #1100, especially for the examples : result always in a `result` variable, result displayed in a comment (`//`);

2024-05-13 15:39 UTC, vibenedict commented
@ivpavici @PhilippeR26

2024-05-14 12:02 UTC, ivpavici requested changes

2024-05-14 12:02 UTC, ivpavici commented on src/utils/provider.ts
> + *
missing returns

2024-05-14 12:02 UTC, ivpavici commented on src/utils/provider.ts
> + *
missing returns

2024-05-14 12:02 UTC, ivpavici commented on src/utils/provider.ts
> + * @example
missing returns

2024-05-14 14:12 UTC, PhilippeR26 requested changes
Some work remains.

2024-05-14 14:12 UTC, PhilippeR26 commented on src/utils/provider.ts
> + * wait(1000) // 1000 milliseconds == 1 second
It's an async function.
You have to add the `await` prefix.
All the functions of this file are in the `provider` space. To correct.

2024-05-14 14:12 UTC, PhilippeR26 commented on src/utils/provider.ts
> + * ```
Last function hasn't been made.

2024-05-14 14:12 UTC, PhilippeR26 commented on src/utils/provider.ts
> + * ```
`createSierraContractClass` and `parseContract` are performing the opposite action of the other, but you have the same example and result for both cases.
You should re-test these examples ; you will quickly find your error.

2024-05-31 09:00 UTC, closed without merging