chore: add documentation for starknetid.ts
starknet-io/starknet.js pull request #1115
Opened 2024-05-01 23:09 UTC by muheebyusufbaba1

## Motivation and Resolution
Closes #1090

### RPC version (if applicable)

...

## Usage related changes

- Change 1.
- ...

## Development related changes

- Change 1.
- ...

## Checklist:

- [x] Performed a self-review of the code
- [x] Rebased to the last commit of the target branch (or merged it into my branch)
- [x] Linked the issues which this PR resolves
- [x] Documented the changes in code (API docs will be generated automatically)
- [x] Updated the tests
- [x] All tests are passing

2024-05-02 12:36 UTC, ivpavici commented on src/utils/starknetId.ts
> + * const result =  useDecoded([3015206943634620n])
```suggestion
 * const result = useDecoded([3015206943634620n])
```

2024-05-02 18:33 UTC, muheebyusufbaba1 commented
@ivpavici

2024-05-03 09:45 UTC, ivpavici commented on src/utils/stark.ts
> + * @example
missing `@returns` here

2024-05-03 09:45 UTC, ivpavici commented on src/utils/stark.ts
> + * @example
missing @returns here

2024-05-03 09:45 UTC, ivpavici commented on src/utils/stark.ts
> + * @example
we can remove for this one, it's deprecated

2024-05-03 09:45 UTC, ivpavici commented on src/utils/stark.ts
>   * Convert estimated fee to max fee with overhead
missing `@param` and `@returns` here

2024-05-03 09:45 UTC, ivpavici commented on src/utils/starknetId.ts
> + * @example
@irisdv can you please confirm if these example's look ok?

2024-05-06 13:59 UTC, ivpavici commented on src/utils/stark.ts
> + * @returns {bigint} The maximum fee with overhead
@example missning!

2024-05-07 13:53 UTC, PhilippeR26 requested changes
Nearly good, but as explained in Telegram https://t.me/c/2066195975/59 ,
please follow very rigorously the template of this PR https://github.com/starknet-io/starknet.js/pull/1100, especially for the examples : result always in a result variable, result displayed in a comment (//) (no assert).

2024-05-13 15:10 UTC, muheebyusufbaba1 commented
Reviews fixed @PhilippeR26

2024-05-14 11:53 UTC, ivpavici commented on src/utils/stark.ts
> + * @returns {bigint} The maximum fee with overhead
@example still missing!

2024-05-14 13:00 UTC, PhilippeR26 requested changes
Is it normal to have no examples or missing @returns in some areas :
starks.ts : L79-106, L168-242 ?

2024-05-31 09:01 UTC, closed without merging