Add test and support for negative Signed integers smaller than 252 bits
starknet-io/starknet.js pull request #1177
Opened 2024-07-05 08:18 UTC by fmmesen

feat: added new data types
test: added new tests for data types

## Motivation and Resolution

Created new Cairo Data Types integer classes and their unit tests for every range of bits below 252, similar to the `uint256.ts` file.

### RPC version (if applicable)

...

## Usage related changes

- Change 1.
- ...

## Development related changes

- Added cairoInt, int8, int16, int32, int64, int128 clases.
- Added tests for every new data type.

## Checklist:

- [ ] Performed a self-review of the code
- [ ] Rebased to the last commit of the target branch (or merged it into my branch)
- [ ] Linked the issues which this PR resolves
- [ ] Documented the changes in code (API docs will be generated automatically)
- [ ] Updated the tests
- [ ] All tests are passing

2024-07-05 08:26 UTC, fmmesen commented
Hello @tabaktoni @ivpavici !
New feature is done and ready to be reviewed.

2024-07-11 09:39 UTC, penovicp requested changes
The purpose of the linked issue isn't to just create the corresponding utility classes but to actually use them for request/response handling.

Also, `CairoInt` looks like it should be an abstract class and the type implementation classes look like they could have improved code reuse.

2024-07-17 16:42 UTC, fmmesen commented
Hello @penovicp, I have a doubt about where exactly I should use those classes for request/response handling. Could you provide some guidance?

2024-07-24 19:01 UTC, penovicp commented
This [comment](https://github.com/starknet-io/starknet.js/issues/1014#issuecomment-2176111160) describes what the required behaviour should be.

The existing data type utility classes such as [CairoUint256](https://github.com/starknet-io/starknet.js/blob/v6.11.0/src/utils/cairoDataTypes/uint256.ts#L18) and [CairoUint512](https://github.com/starknet-io/starknet.js/blob/v6.11.0/src/utils/cairoDataTypes/uint512.ts#L15) can be checked to see how and where the signed integer classes should be used.

2024-10-22 05:41 UTC, fmmesen commented
@penovicp Already used the utility classes, please let me know if you see that I'm missing something

2025-09-08 06:57 UTC, tabaktoni commented
Closing this one in the favor of the new CairoType Classes

2025-09-08 06:57 UTC, closed without merging