test getInvokeEstimateFee
starknet-io/starknet.js pull request #735
Opened 2023-08-29 07:14 UTC by financegeek-org

## Motivation and Resolution
Requested in https://github.com/0xs34n/starknet.js/issues/589

...

### RPC version (if applicable)

...

## Usage related changes
N/A

## Development related changes
N/A; SDK test

## Checklist:

- [X] Performed a self-review of the code
- [X] Rebased to the last commit of the target branch (or merged it into my branch)
- [X] Linked the issues which this PR resolves
- [ ] Documented the changes in code (API docs will be generated automatically)
- [X] Updated the tests
- [ ] All tests are passing

2023-08-29 08:31 UTC, ivpavici approved these changes
lgtm

2023-08-29 08:46 UTC, tabaktoni requested changes
1. Testing this is redundant but if we test it as unit then it should be tested for both providers RPC and Sequencer.
2. Multiple linting issues fixed suggested
3. LibraryError: 20: Contract not found when test run: You can't ping random address
4. You are testing that method is called but you called it with `rpcProvider.getInvokeEstimateFee` unnecessary test
5. You do not test the execution of this method nor its functional or execution response.

In short, nothing is correct in this PR.
I recommend setting it to draft until it is completed, or closing it and publishing fixed one
If you need help with improving comprehension ping us on Discord and we will be glad to assist with it.

2023-08-29 08:46 UTC, tabaktoni commented on __tests__/rpcProvider.test.ts
> +      }
Multiple linting issues

```suggestion
      };
```

2023-08-29 08:46 UTC, tabaktoni commented on __tests__/rpcProvider.test.ts
> +
```suggestion
```

2023-08-29 08:46 UTC, tabaktoni commented on __tests__/rpcProvider.test.ts
> +      }
```suggestion
      };
```

2023-08-29 08:46 UTC, tabaktoni commented on __tests__/rpcProvider.test.ts
> +      const transaction = await rpcProvider.getInvokeEstimateFee(
transaction var is not used
```suggestion
      await rpcProvider.getInvokeEstimateFee(
```

2023-08-30 00:51 UTC, financegeek-org commented
> 2. Multiple linting issues fixed suggested
Updated, thanks!

> 3. LibraryError: 20: Contract not found when test run: You can't ping random address
So create a contract and deploy, then test that? 🤔 

> 4. You are testing that method is called but you called it with `rpcProvider.getInvokeEstimateFee` unnecessary test
It's testing getInvokeEstimateFee by checking that fetchEndpoint is called with parameter starknet_estimateFee.

> 5. You do not test the execution of this method nor its functional or execution response.
Suggestions on how to test this?

2024-03-04 11:12 UTC, penovicp commented
Closing this because the underlying code has undergone significant changes. Ask in the corresponding issue if you want to make another attempt.

2024-03-04 11:12 UTC, closed without merging